// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjRgaW4grcJ1kzgvMw2KG9x1PAyZ99Mi0',
    appId: '1:601500736081:android:3c2040edd4ae9143953670',
    messagingSenderId: '601500736081',
    projectId: 'water-management-system-f1a5c',
    storageBucket: 'water-management-system-f1a5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtKUTgoywKQ3j3a19IWyEGyXkT7pSk1R4',
    appId: '1:601500736081:ios:9849c46e9cbb7492953670',
    messagingSenderId: '601500736081',
    projectId: 'water-management-system-f1a5c',
    storageBucket: 'water-management-system-f1a5c.firebasestorage.app',
    iosBundleId: 'com.example.waterManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtKUTgoywKQ3j3a19IWyEGyXkT7pSk1R4',
    appId: '1:601500736081:ios:9849c46e9cbb7492953670',
    messagingSenderId: '601500736081',
    projectId: 'water-management-system-f1a5c',
    storageBucket: 'water-management-system-f1a5c.firebasestorage.app',
    iosBundleId: 'com.example.waterManagementSystem',
  );
}
